<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VSBTU4D1" failures="2" tests="11" name="Report Test" time="253.262" errors="0" timestamp="2020-12-24T10:48:20 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="27.524"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="17.267"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="16.213"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="16.569"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="15.899"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="13.744"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="15.408"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="30.58"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="39.601"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="29.195">
    <failure type="java.lang.AssertionError" message="When user does not select any checkbox to save, still shows successful message on click">
      <![CDATA[java.lang.AssertionError: When user does not select any checkbox to save, still shows successful message on click
at org.junit.Assert.fail(Assert.java:89)
at configurePIM.StepDefConfigurePIM.error_message_is_displayed_or_user_is_prompted_that_no_field_is_chosen(StepDefConfigurePIM.java:155)
at ✽.error message is displayed or user is prompted that no field is chosen(classpath:configurePIM/configurePIM.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="30.195">
    <failure type="java.lang.AssertionError" message="successful message is shown for adding a new reporting method">
      <![CDATA[java.lang.AssertionError: successful message is shown for adding a new reporting method
at org.junit.Assert.fail(Assert.java:89)
at reportingmethods.StepDefAddReportingMethod.a_new_reporting_method_is_added_as_message_is_displayed(StepDefAddReportingMethod.java:119)
at ✽.a new Reporting Method is added as message is displayed(classpath:reportingmethods/addreportingmethod.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Report Test -->
